---
- name: Add Azure Cloud Credentials to AWX (Token Authentication)
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    awx_host: "http://172.17.0.1:8052"
    awx_token: "dLzd4hXxJ7iOcdpkU0hZKK1ZN6reR0"
    encoded_azure_credtype: "{{ 'Microsoft Azure Resource Manager' | urlencode }}"
    credential_name: "Azure_{{ organization }}_{{ Name[:8] }}"

  tasks:

    - name: Display input parameters
      debug:
        msg:
          - "Subscription ID: {{ Name }}"
          - "Application ID: {{ client }}"
          - "Tenant ID: {{ tenant }}"
          - "Organization: {{ organization }}"
          - "Credential Name: {{ credential_name }}"

    # -------------------- GET ORGANIZATION --------------------
    - name: Get organization ID
      uri:
        url: "{{ awx_host }}/api/v2/organizations/?name={{ organization }}"
        method: GET
        headers:
          Authorization: "Bearer {{ awx_token }}"
        validate_certs: no
      register: org_response

    - name: Set organization ID
      set_fact:
        org_id: "{{ org_response.json.results[0].id }}"
      when: org_response.json.count > 0

    - name: Fail if organization not found
      fail:
        msg: "❌ Organization '{{ organization }}' not found in AWX."
      when: org_response.json.count == 0

    # -------------------- GET CREDENTIAL TYPE --------------------
    - name: Get Azure credential type ID
      uri:
        url: "{{ awx_host }}/api/v2/credential_types/?name={{ encoded_azure_credtype }}"
        method: GET
        headers:
          Authorization: "Bearer {{ awx_token }}"
        validate_certs: no
      register: cred_type_response

    - name: Set credential type ID
      set_fact:
        cred_type_id: "{{ cred_type_response.json.results[0].id }}"
      when: cred_type_response.json.count > 0

    - name: Fail if credential type missing
      fail:
        msg: "❌ Azure Credential Type not found in AWX!"
      when: cred_type_response.json.count == 0

    # -------------------- CHECK IF CREDS EXIST --------------------
    - name: Check if credential already exists
      uri:
        url: "{{ awx_host }}/api/v2/credentials/?name={{ credential_name }}"
        method: GET
        headers:
          Authorization: "Bearer {{ awx_token }}"
        validate_certs: no
      register: existing_cred

    # -------------------- CREATE --------------------
    - name: Create Azure Credential in AWX
      uri:
        url: "{{ awx_host }}/api/v2/credentials/"
        method: POST
        headers:
          Authorization: "Bearer {{ awx_token }}"
          Content-Type: "application/json"
        body_format: json
        status_code: [200, 201]
        validate_certs: no
        body:
          name: "{{ credential_name }}"
          description: "Azure credential for {{ organization }}"
          organization: "{{ org_id }}"
          credential_type: "{{ cred_type_id }}"
          inputs:
            subscription: "{{ Name }}"
            client: "{{ client }}"
            secret: "{{ secret }}"
            tenant: "{{ tenant }}"
      register: azure_created
      when: existing_cred.json.count == 0

    # -------------------- UPDATE --------------------
    - name: Update existing Azure Credential
      uri:
        url: "{{ awx_host }}/api/v2/credentials/{{ existing_cred.json.results[0].id }}/"
        method: PATCH
        headers:
          Authorization: "Bearer {{ awx_token }}"
          Content-Type: "application/json"
        body_format: json
        status_code: [200, 201]
        validate_certs: no
        body:
          description: "Azure credential for {{ organization }} (updated)"
          inputs:
            subscription: "{{ Name }}"
            client: "{{ client }}"
            secret: "{{ secret }}"
            tenant: "{{ tenant }}"
      register: azure_updated
      when: existing_cred.json.count > 0

    # -------------------- SUMMARY --------------------
    - name: Display success message
      debug:
        msg:
          - "✅ Azure Credential successfully {{ 'created' if existing_cred.json.count == 0 else 'updated' }}"
          - "Organization: {{ organization }}"
          - "Credential Name: {{ credential_name }}"
          - "Credential ID: {{ azure_created.json.id | default(existing_cred.json.results[0].id) }}"

