---
- name: Add Azure Cloud Credentials to AWX
  hosts: localhost
  connection: local
  gather_facts: no
  
  vars:
    awx_host: "http://localhost:8052"
    awx_username: "admin"
    awx_password: "admin"
    credential_name: "Azure_{{ organization }}_{{ Name[:8] }}"

  tasks:
    - name: Display input parameters
      debug:
        msg:
          - "Subscription ID: {{ Name }}"
          - "Application ID: {{ description }}"
          - "Organization: {{ organization }}"
          - "Credential Name: {{ credential_name }}"

    - name: Get organization ID
      uri:
        url: "{{ awx_host }}/api/v2/organizations/?name={{ organization }}"
        method: GET
        user: "{{ awx_username }}"
        password: "{{ awx_password }}"
        force_basic_auth: yes
        validate_certs: no
        return_content: yes
      register: org_response

    - name: Set organization ID
      set_fact:
        org_id: "{{ org_response.json.results[0].id }}"
      when: org_response.json.count > 0

    - name: Fail if organization not found
      fail:
        msg: "Organization '{{ organization }}' not found in AWX"
      when: org_response.json.count == 0

    - name: Get Azure credential type ID
      uri:
        url: "{{ awx_host }}/api/v2/credential_types/?name=Microsoft Azure Resource Manager"
        method: GET
        user: "{{ awx_username }}"
        password: "{{ awx_password }}"
        force_basic_auth: yes
        validate_certs: no
        return_content: yes
      register: cred_type_response

    - name: Set credential type ID
      set_fact:
        cred_type_id: "{{ cred_type_response.json.results[0].id }}"
      when: cred_type_response.json.count > 0

    - name: Check if credential already exists
      uri:
        url: "{{ awx_host }}/api/v2/credentials/?name={{ credential_name }}"
        method: GET
        user: "{{ awx_username }}"
        password: "{{ awx_password }}"
        force_basic_auth: yes
        validate_certs: no
        return_content: yes
      register: existing_cred

    - name: Create Azure Credential in AWX
      uri:
        url: "{{ awx_host }}/api/v2/credentials/"
        method: POST
        user: "{{ awx_username }}"
        password: "{{ awx_password }}"
        force_basic_auth: yes
        body_format: json
        validate_certs: no
        status_code: [200, 201]
        body:
          name: "{{ credential_name }}"
          description: "Azure credential for {{ organization }}"
          organization: "{{ org_id }}"
          credential_type: "{{ cred_type_id }}"
          inputs:
            subscription: "{{ Name }}"
            client: "{{ client }}"
            secret: "{{ secret }}"
            tenant: "{{ tenant }}"
      register: azure_credential
      when: existing_cred.json.count == 0

    - name: Update existing Azure Credential
      uri:
        url: "{{ awx_host }}/api/v2/credentials/{{ existing_cred.json.results[0].id }}/"
        method: PATCH
        user: "{{ awx_username }}"
        password: "{{ awx_password }}"
        force_basic_auth: yes
        body_format: json
        validate_certs: no
        status_code: [200, 201]
        body:
          description: "Azure credential for {{ organization }} (updated)"
          inputs:
            subscription: "{{ Name }}"
            client: "{{ client }}"
            secret: "{{ secret }}"
            tenant: "{{ tenant }}"
      register: azure_credential_updated
      when: existing_cred.json.count > 0

    - name: Display success message
      debug:
        msg: 
          - "✓ Azure cloud credentials added successfully!"
          - "Organization: {{ organization }}"
          - "Credential Name: {{ credential_name }}"
          - "Credential ID: {{ azure_credential.json.id | default(existing_cred.json.results[0].id) }}"
