---
- name: Azure Login Only
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Azure Login using Service Principal (exact CLI command)
      shell: >
        /usr/local/bin/az login --service-principal
        --username "{{ client_id_var }}"
        --password "{{ client_secret_var }}"
        --tenant "{{ tenant_id_var }}"
      environment:
        PATH: "/usr/local/bin:/usr/bin:/bin"
      register: login_output

    - name: Show login result
      debug:
        var: login_output.stdout
