---
- name: Azure Login and Fetch VMs + Send to Next.js API
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    az_path: "/usr/bin/az"   # working Azure CLI
    url: "http://172.17.0.1:3000/api/saveInstanceDetails"
  tasks:
    - name: Azure Login using Service Principal
      shell: >
        {{ az_path }} login --service-principal
        --username "{{ client_id_var }}"
        --password "{{ client_secret_var }}"
        --tenant "{{ tenant_id_var }}"
      environment:
        PATH: "/usr/bin:/usr/local/bin:/bin"
      register: azure_login
      failed_when: azure_login.rc != 0
      changed_when: false

    - name: Set Azure Subscription
      shell: "{{ az_path }} account set --subscription {{ subscription_id_var }}"
      environment:
        PATH: "/usr/bin:/usr/local/bin:/bin"
      register: set_subscription
      failed_when: set_subscription.rc != 0
      changed_when: false

    - name: Fetch VM list
      shell: "{{ az_path }} vm list --subscription {{ subscription_id_var }} --output json"
      environment:
        PATH: "/usr/bin:/usr/local/bin:/bin"
      register: vm_list_raw
      failed_when: vm_list_raw.rc != 0

    - name: Parse VM list safely
      set_fact:
        azure_vm_list: "{{ (vm_list_raw.stdout | default('[]')) | from_json }}"

    - name: Fetch VM Details
      shell: >
        {{ az_path }} vm show
        --resource-group {{ item.resourceGroup }}
        --name {{ item.name }}
        --show-details
        --output json
      environment:
        PATH: "/usr/bin:/usr/local/bin:/bin"
      loop: "{{ azure_vm_list }}"
      register: vm_detail_raw
      when: azure_vm_list | length > 0

    - name: Parse VM details safely
      set_fact:
        vm_details: "{{ (vm_detail_raw.results | map(attribute='stdout') | map('from_json') | list) | default([]) }}"
      when: azure_vm_list | length > 0

    - name: Show VM details
      debug:
        var: vm_details

    - name: Post VM details to Next.js API
      uri:
        url: "{{ nextjs_instance_api }}"
        method: POST
        body: "{{ vm_details | to_json }}"
        headers:
          Content-Type: "application/json"
        status_code: [200,201]
      when: azure_vm_list | length > 0

    - name: Logout Azure
      shell: "{{ az_path }} logout"
      environment:
        PATH: "/usr/bin:/usr/local/bin:/bin"
      ignore_errors: yes
